<?php
/**
*
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to tech@dotpay.pl so we can send you a copy immediately.
*
*
*  @author    Dotpay Team <tech@dotpay.pl>
*  @copyright Dotpay
*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*
*/
?>

<ul class="form-list" id="payment_form_dotpay" style="display: none">
    <li>
        <p><?php echo Mage::helper('dotpay')->__('You will be redirected to our secure payment page where you can pay for your order.'); ?></p>
        <?php if ($src = $this->getPaymentImageSrc()): ?>
        <img src="<?php echo $src ?>"/>
        <?php endif ?>
    </li>
</ul>
