<?php
/**
*
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to tech@dotpay.pl so we can send you a copy immediately.
*
*
*  @author    Dotpay Team <tech@dotpay.pl>
*  @copyright Dotpay
*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*
*/
?>

<?php if($this->isWidgetMode()): ?>
<h3><?php echo Mage::helper('dotpay')->__('Please select your payment channel'); ?></h3>
<script>
    function onChooseChannel(e) {
        window.dotpayWidget.jQuery('#dotpay_dotpay_redirection_form #submit').attr('disabled', true);
        window.dotpayWidget.jQuery.post('<?php echo $this->getSignatureUrl(); ?>',
            {"order":<?php echo $this->getOrderId(); ?>, "channel": e.channel.id},
            function(chk){
                window.dotpayWidget.jQuery('#dotpay_dotpay_redirection_form #chk').val(chk);
                window.dotpayWidget.jQuery('#dotpay_dotpay_redirection_form #submit').attr('disabled', false);
            }
        );
    }
    var dotpayConfig = {
        payment: {
            sellerId: <?php echo $this->getSellerId(); ?>,
            amount: <?php echo round($this->getCurrentOrder()->getGrandTotal(), 2); ?>,
            currency: '<?php echo $this->getCurrentOrder()->getOrderCurrencyCode(); ?>',
            lang: '<?php echo $this->getLangCode(); ?>'
        },
        request: {
            test: 
			<?php
				if((bool)$this->isTestMode() == 1){ echo '1';}else {echo '0';}
			?> },
        event: {
            onChoose: onChooseChannel
        }

    };

	 if (window.dotpayWidget != undefined) {
			window.dotpayWidget.jQuery(document).ready(function(){
				window.dotpayWidget.jQuery('#dotpay_dotpay_redirection_form #submit').attr('disabled', true);
				window.dotpayWidget.init(dotpayConfig);
			});
	 }
</script>
<?php else: ?>
<script>
    jQuery(document).ready(function(){
        jQuery('#dotpay_dotpay_redirection_form').submit();
    });
</script>
<?php endif; ?>
<?php echo $this->getForm()->toHtml() ?>